steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t',
        'europe-southwest1-docker.pkg.dev/microservicios-dev-434019/img-registro-ms/orders-ms',
        '-f',
        'dockerfile.prod',
        '--platform=linux/amd64',
        '--build-arg',
        'CONNECTION_STRING=$CONNECTION_STRING',
        '.',
      ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-southwest1-docker.pkg.dev/microservicios-dev-434019/img-registro-ms/orders-ms']
options:
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _CONNECTION_STRING: 'postgresql://orders-db_owner:hpFYvf7c6xRD@ep-dry-sun-a2c8njxz.eu-central-1.aws.neon.tech/orders-db?sslmode=require'
